name: CD - Continuous Deployment

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  # Job 1: Construye, sube la imagen y despliega a Stage
  build-and-deploy-stage:
    name: Build, Push & Deploy to Stage
    runs-on: ubuntu-latest
    environment:
      name: dev
    outputs:
      image_sha: ${{ steps.build-image.outputs.image_sha }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      run: |
        ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG_SHA=$(echo ${{ github.sha }} | cut -c1-7)
        FULL_IMAGE_NAME="$ECR_REGISTRY/${{ vars.ECR_REPOSITORY }}:$IMAGE_TAG_SHA"
        
        docker build -t $FULL_IMAGE_NAME .
        docker tag $FULL_IMAGE_NAME $ECR_REGISTRY/${{ vars.ECR_REPOSITORY }}:latest
        
        docker push $FULL_IMAGE_NAME
        docker push $ECR_REGISTRY/${{ vars.ECR_REPOSITORY }}:latest
        
        echo "image_sha=$FULL_IMAGE_NAME" >> $GITHUB_OUTPUT
    - name: Update App Runner (Stage) with new image
      run: |
        aws apprunner update-service \
          --service-arn ${{ secrets.APP_RUNNER_SERVICE_ARN_STG }} \
          --source-configuration '{
            "ImageRepository": {
              "ImageIdentifier": "${{ steps.build-image.outputs.image_sha }}",
              "ImageRepositoryType": "ECR"
            }
          }'

    - name: Verify Job Output
      run: |
        echo "Verificación: El output 'image_sha' se ha establecido como: ${{ steps.build-image.outputs.image_sha }}"

  # Job 2: Despliega a Producción
  deploy-prod:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [build-and-deploy-stage]
    environment:
      name: production 

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Update App Runner (Production) with new image
      env:
        IMAGE_IDENTIFIER: $ECR_REGISTRY/${{ vars.ECR_REPOSITORY }}:$IMAGE_TAG_SHA
      run: |
        echo "Aprobación recibida. Desplegando la imagen: $IMAGE_IDENTIFIER"

        aws apprunner update-service \
          --service-arn ${{ secrets.APP_RUNNER_SERVICE_ARN_PRD }} \
          --source-configuration '{
            "ImageRepository": {
              "ImageIdentifier": "'"$IMAGE_IDENTIFIER"'",
              "ImageRepositoryType": "ECR"
            }
          }'
          
  # Job 3: Notificación final
  notify-final:
    name: Final Deploy Results
    runs-on: ubuntu-latest
    needs: [build-and-deploy-stage, deploy-prod]
    if: always()
    steps:
    - name: Notification
      run: |
        if [[ "${{ needs.build-and-deploy-stage.result }}" == "success" && "${{ needs.deploy-prod.result }}" == "success" ]]; then
          echo "🎉 Despliegue completado con éxito en Stage y Producción!"
        elif [[ "${{ needs.build-and-deploy-stage.result }}" != "success" ]]; then
          echo "❌ Falló la construcción o el despliegue a Stage."
          exit 1
        else
          echo "❌ Falló el despliegue a Producción después de la aprobación."
          exit 1
        fi
